/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Clases.Observacion;
import Clases.Piloto;
import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author HP
 */
public class Reportefeedback extends javax.swing.JFrame {
     private ArrayList<Piloto> listaPilotos = new ArrayList<>(); // Lista para almacenar los pilotos
    private ArrayList<Observacion> listaObservaciones = new ArrayList<>(); // Lista para almacenar las observaciones

    /**
     * Creates new form Reportefeedback
     */
    public Reportefeedback() {
        initComponents();
         cargarPilotos(); // Cargar los nombres de los pilotos
        cargarObservaciones(); // Cargar las observaciones desde el archivo
        refrescarTabla(); 
        getContentPane().setBackground(new java.awt.Color(102, 102, 102));
        setLocationRelativeTo(null);
        setSize(430, 620); // Establece el tamaño fijo de la ventana
        setResizable(false); // Evita que el usuario cambie el tamaño
    }

    
private void cargarPilotos() {
       CboxPilotos.removeAllItems();
        cargarDesdeArchivo();

        for (Piloto piloto : listaPilotos) {
            CboxPilotos.addItem(piloto.getNombre());
        }
    }

    private void cargarDesdeArchivo() {
         String archivoPilotos = "Pilotos";
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream(archivoPilotos))) {
            listaPilotos = (ArrayList<Piloto>) ois.readObject();
        } catch (FileNotFoundException e) {
            System.out.println("Archivo no encontrado, se creará uno nuevo al guardar.");
        } catch (IOException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar desde archivo: " + e.getMessage());
        }
    }
    private void cargarObservaciones() {
        String archivoObservaciones = "observaciones"; // Nombre del archivo donde se guardan las observaciones
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream(archivoObservaciones))) {
            listaObservaciones = (ArrayList<Observacion>) ois.readObject();
        } catch (FileNotFoundException e) {
            System.out.println("Archivo de observaciones no encontrado, se creará uno nuevo al guardar.");
        } catch (IOException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar observaciones: " + e.getMessage());
        }
    }
private void guardarObservaciones() {
         String archivoObservaciones = "observaciones";
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(archivoObservaciones))) {
            oos.writeObject(listaObservaciones);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar observaciones: " + e.getMessage());
        }
    }
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CboxPilotos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        btnAnadir = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CboxPilotos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setText("Pilotos");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setText("Observaciones");

        txtObservaciones.setBackground(new java.awt.Color(204, 204, 204));
        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtObservaciones);

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
<<<<<<< HEAD
                "Pilotos", "Observaciones"
=======
                "Piloto", "Observacion"
>>>>>>> 608f94393de76739d52dec1f1f856bb16b5124ca
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnAnadir.setText("Añadir");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel8.setText("Reporte de Pilotos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBorrar))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(CboxPilotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAnadir))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnRegresar)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CboxPilotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnAnadir))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnBorrar))
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        // TODO add your handling code here:
        String pilotoSeleccionado = (String) CboxPilotos.getSelectedItem();
        String observacion = txtObservaciones.getText().trim();
        if (pilotoSeleccionado != null && !observacion.isEmpty()) {
            Observacion nuevaObservacion = new Observacion(pilotoSeleccionado, observacion);
            listaObservaciones.add(nuevaObservacion);
            guardarObservaciones();
            refrescarTabla();
            txtObservaciones.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Por favor selecciona un piloto y escribe una observación.");
        }
    }//GEN-LAST:event_btnAnadirActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            listaObservaciones.remove(selectedRow);
            guardarObservaciones();
            refrescarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Por favor selecciona una observación para borrar.");
        }
    }//GEN-LAST:event_btnBorrarActionPerformed
 private void refrescarTabla() {
        // Limpiar la tabla antes de agregar nuevas filas
         javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        if (listaObservaciones == null || listaObservaciones.isEmpty()) {
            return;
        }

        for (Observacion observacion : listaObservaciones) {
            model.addRow(new Object[]{
                observacion.getPilotoNombre(),
                observacion.getObservacion()
            });
        }

        javax.swing.table.TableColumnModel columnModel = jTable1.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(100);
        columnModel.getColumn(1).setPreferredWidth(300);

        jTable1.getColumnModel().getColumn(1).setCellRenderer(new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (c instanceof javax.swing.JLabel) {
                    javax.swing.JLabel label = (javax.swing.JLabel) c;
                    label.setVerticalAlignment(javax.swing.JLabel.TOP);
                }
                return c;
            }
        });

        for (int row = 0; row < jTable1.getRowCount(); row++) {
            int rowHeight = 25;
            String observacionText = (String) model.getValueAt(row, 1);
            if (observacionText != null && !observacionText.isEmpty()) {
                java.awt.FontMetrics fm = jTable1.getFontMetrics(jTable1.getFont());
                int textWidth = columnModel.getColumn(1).getWidth();
                if (textWidth > 0) {
                    int lines = (fm.stringWidth(observacionText) / textWidth) + 1;
                    rowHeight = Math.max(rowHeight, lines * fm.getHeight());
                }
            }
            jTable1.setRowHeight(row, rowHeight);
        }
    }
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
<<<<<<< HEAD
        // TODO add your handling code here:
         MenuPrincipal objMenuPrincipal = new MenuPrincipal();
        this.setVisible(false);
        objMenuPrincipal.setVisible(true);
=======
        MenuPrincipal objMenuPrincipal = new MenuPrincipal();
        objMenuPrincipal.setVisible(true); // Muestra el menú principal
        this.dispose();
        
>>>>>>> 608f94393de76739d52dec1f1f856bb16b5124ca
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportefeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new Reportefeedback().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboxPilotos;
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
